import { z } from "zod";
import { categoryTool, bp, type ToolDef } from "../types.js";
import { Color } from "../schemas.js";

export const materialTool: ToolDef = categoryTool(
  "material",
  "Materials: create, read, parameters, shading, textures, and graph authoring (expression nodes, connections).",
  {
    read:              bp("Read material structure. Params: assetPath", "read_material", (p) => ({ assetPath: p.assetPath })),
    list_parameters:   bp("List overridable parameters. Params: assetPath", "list_material_parameters", (p) => ({ assetPath: p.assetPath })),
    set_parameter:     bp("Set parameter on MaterialInstance. Params: assetPath, parameterName, parameterType, value", "set_material_parameter"),
    set_expression_value: bp("Set value on expression node. Params: materialPath, expressionIndex, value", "set_expression_value"),
    disconnect_property: bp("Disconnect a material property input. Params: materialPath, property", "disconnect_material_property"),
    create_instance:   bp("Create material instance. Params: parentPath, name?, packagePath?", "create_material_instance"),
    create:            bp("Create material. Params: name, packagePath?", "create_material"),
    set_shading_model: bp("Set shading model. Params: assetPath, shadingModel", "set_material_shading_model"),
    set_blend_mode:    bp("Set blend mode. Params: assetPath, blendMode", "set_material_blend_mode"),
    set_base_color:    bp("Set base color. Params: assetPath, color", "set_material_base_color"),
    connect_texture:   bp("Connect texture to property. Params: materialPath, texturePath, property", "connect_texture_to_material"),
    add_expression:    bp("Add expression node. Params: materialPath, expressionType, name?, parameterName?", "add_material_expression"),
    connect_expressions: bp("Wire two expressions. Params: materialPath, sourceExpression, sourceOutput?, targetExpression, targetInput?", "connect_material_expressions"),
    connect_to_property: bp("Wire expression to material output. Params: materialPath, expressionName, outputName?, property", "connect_to_material_property"),
    list_expressions:  bp("List expression nodes. Params: materialPath", "list_material_expressions"),
    delete_expression: bp("Remove expression. Params: materialPath, expressionName", "delete_material_expression"),
    list_expression_types: bp("List available expression types", "list_expression_types"),
    recompile:         bp("Recompile material. Params: materialPath", "recompile_material"),
  },
  undefined,
  {
    assetPath: z.string().optional(),
    parameterName: z.string().optional(),
    parameterType: z.string().optional().describe("Parameter type for set_parameter: scalar, vector, texture"),
    expressionIndex: z.number().optional(),
    value: z.unknown().optional(),
    parentPath: z.string().optional(),
    name: z.string().optional(),
    packagePath: z.string().optional(),
    shadingModel: z.string().optional(),
    blendMode: z.string().optional().describe("Blend mode: Opaque, Masked, Translucent, Additive, Modulate, AlphaComposite, AlphaHoldout"),
    color: Color.optional(),
    materialPath: z.string().optional(),
    texturePath: z.string().optional(),
    property: z.string().optional().describe("Material property: BaseColor, Normal, Roughness, Metallic, EmissiveColor, etc."),
    expressionType: z.string().optional().describe("Expression type: Constant, TextureSample, Multiply, Lerp, ScalarParameter, etc."),
    x: z.number().optional(), y: z.number().optional(),
    properties: z.record(z.unknown()).optional(),
    sourceExpression: z.string().optional(),
    sourceOutput: z.string().optional(),
    targetExpression: z.string().optional(),
    targetInput: z.string().optional(),
    expressionName: z.string().optional(),
    outputName: z.string().optional(),
  },
);
